name: Update README ⭐
on:
  schedule:
    - cron: "*/15 * * * *"  # Every 4 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: ${{ secrets.AOC_UID }}
          leaderboardId: ${{ secrets.AOC_LEADERBOARD }}
          sessionCookie: ${{ secrets.AOC_SESSION }}
          year: 2022
      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: ${{ secrets.AOC_UID }}
          session: ${{ secrets.AOC_SESSION }}
          
#         Optional inputs:
#         
          year: 2022
#          leaderboard: 'https://adventofcode.com/2022/leaderboard/private/view/277540.json'               # The url of the leaderboard from witch the data is fetched. Typically your private leaderboard.
#         file: 'README.md'                                                                              # The file that contains the badges
#         dayRegex: '(?<=https:\/\/img\.shields\.io\/badge\/day%20📅-)[0-9]+(?=-blue)'                   # Regular expression that finds the content of the day badge in your file.
#         starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/stars%20⭐-)[0-9]+(?=-yellow)'             # Regular expression that finds the content of the stars badge in your file.
#         daysCompletedRegex: '(?<=https:\/\/img\.shields\.io\/badge\/days%20completed-)[0-9]+(?=-red)'  # Regular expression that finds the content of the days completed badge iun your file.

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stars